// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/Books/Mathematics_for_Class_7/Probability.tsx";
import * as $1 from "./routes/Topics.tsx";
import * as $2 from "./routes/[name].tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Books.tsx";
import * as $$1 from "./islands/Chapters.tsx";
import * as $$2 from "./islands/Contents.tsx";
import * as $$3 from "./islands/Counter.tsx";
import * as $$4 from "./islands/Navbar.tsx";

const manifest = {
  routes: {
    "./routes/Books/Mathematics_for_Class_7/Probability.tsx": $0,
    "./routes/Topics.tsx": $1,
    "./routes/[name].tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Books.tsx": $$0,
    "./islands/Chapters.tsx": $$1,
    "./islands/Contents.tsx": $$2,
    "./islands/Counter.tsx": $$3,
    "./islands/Navbar.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
